### ISSUE TITLE
Make a new release please

### ISSUE THREAD

**Issue by nvanheuverzwijn** [JoeNyland/puppet-cloudwatch#30]
@JoeNyland Hi, could make a new release with the latest change please ? 

Thank you so much for your work !

**Comment by JoeNyland** [comment]
Hi @nvanheuverzwijn !

Sure, I'll try and get a release out over the next couple of days. Sorry for the delay.

**Comment by JoeNyland** [comment]
I've just pushed a new release: https://forge.puppet.com/MasterRoot24/cloudwatch/0.6.0

**Comment by nvanheuverzwijn** [comment]
@JoeNyland Hey Joe, thank you very much, I really appreciate. Have a great day !
