### ISSUE TITLE
Update to work with Puppet 6

### ISSUE THREAD

**Issue by JoeNyland** [JoeNyland/puppet-cloudwatch#32]
On Puppet 6.0.2 the following error is displayed when you run `rake test`:

```
Evaluation Error: Error while evaluating a Resource Statement, Unknown resource type: 'cron' (file: /Users/joenyland/Code/puppet-cloudwatch/spec/fixtures/modules/cloudwatch/manifests/init.pp, line: 282, column: 5) on node joes-mbp.home
```

**Comment by antoinedeschenes** [comment]
cron is available through module 'puppet-cron' as a library from puppet 6

**Comment by JoeNyland** [comment]
Looks like this issue is no longer there. I don't get the above error when running `rake test` on Puppet 6.
